version: "3.8"

services:
  docker-service-exporter:
    build:
      context: .
    container_name: service-exporter
    environment:
      - DOCKER_HOSTNAME={{.Node.Hostname}}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "9000:9000"